# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:           pretty

# Setup
url:                 http://google.com

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               Eric Lee

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  I'm a CS major at UT Austin. I like to do projects and play [smash](https://en.wikipedia.org/wiki/Super_Smash_Bros._Melee).

# The tags listed as entries in the sidebar
sidebar_tags:        []

# Fallback image and color if not overwritten for tag or post
image:               /public/img/succulent-blurry.jpg
color:               '#FF7B00'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Eric Lee'

  # This photo will be used in the about section
  photo:             /public/img/weird-face-square.png
  photo2x:           /public/img/weird-face-square.png

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    I'm Eric Lee, and I'm trying to blog.

  # Social media icons in sidebar # Comment/uncommet to show/hide # Icons appear in order, can be rearranged:
  social:
    #facebook:        _username_
    #twitter:         _username_
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    github:            ericlee123
    soundcloud:        timeline62x
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-68442991-1'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
